[package]
name = "swc-jsx-dom-runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true

[dependencies]
serde = "1"
swc_core = { version = "77.0.*", features = [
  "ecma_utils",
  "ecma_plugin_transform",
  "ecma_parser",
  "ecma_codegen",
  "testing_transform",
] }

[dev-dependencies]
testing = "27.0.0"

# .cargo/config.toml defines few alias to build plugin.
# cargo build-wasip1 generates wasm32-wasip1 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
